### PR TITLE
Install coverage for project tests.

### PR DESCRIPTION
**Pull request by gnott**
Re issue https://github.com/elifesciences/decision-letter-parser/issues/6, I think this is one way so `coverage` is available when running tests. The travis-ci tests seem to not need this because `coveralls` is installed before `tox` is invoked.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
```
[2019-09-19T01:46:57.147Z] Submitting coverage to coveralls.io...
[2019-09-19T01:46:57.720Z] Coverage submitted!
[2019-09-19T01:46:57.720Z] Job #1.1
[2019-09-19T01:46:57.720Z] https://coveralls.io/jobs/53419768
```

**Comment by gnott** [comment]
Oh, whoops, the error I was seeing is still in the log,

```
ERROR: InvocationError: could not find executable 'coverage'
```

I should be putting the `pip install coverage` prior to the `tox` call in `project_tests.sh` I think.

**Comment by gnott** [comment]
I was trying to get rid of the error as I mentioned above. I changed it so `coveralls` is installed before `tox` is run, and `coverage` is a requirement for `coveralls`.

**Comment by gnott** [comment]
Hmm, I think I solved the install of `coverage` with the latest commit, unfortunately it looks like previously Alfred was green even though it didn't run any tests. Now that coverage is executable, there are 14 failures all related to not finding `pandoc`, yet Alfred also reports as green.

This PR for its purpose is probably correct (if you think so @giorgiosironi). The installation of `pandoc` still looks to be an issue. I solved the pandoc situation separately for travis-ci tests using a Debian package install.

**Comment by giorgiosironi** [comment]
Still approved, but solving the test failure [separately](https://github.com/elifesciences/decision-letter-parser/pull/30).

**Comment by gnott** [comment]
Merged in the docker call experiment, and Alfred is green. The pandoc Docker tests take `194.65 seconds` vs. `3.12 seconds` on travis-ci tests using native `pandoc`, but still, it is green and running, which I hope to see all the time. Merging!

**Comment by gnott** [comment]
That was the worst case scenario for test running though, which also involved downloading the pandoc Docker image. It looks like a more normal test duration is `25.57 seconds` when the docker image is available on the ci server already.

**Pull request merged**
